// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
export {
  getSettings, updateSettings, isCloudEnabled, getCloudUrl,
  getProviderConnections, getProviderConnectionById,
  createProviderConnection, updateProviderConnection,
  deleteProviderConnection, deleteProviderConnectionsByProvider,
  reorderProviderConnections, cleanupProviderConnections,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool,
  getApiKeys, getApiKeyById, createApiKey, updateApiKey, deleteApiKey,
  validateApiKey, resolveApiKeyUserId, isApiKeyValid,
  getCombos, getComboById, getComboByName,
  createCombo, updateCombo, deleteCombo,
  getModelAliases, setModelAlias, deleteModelAlias,
  getCustomModels, addCustomModel, deleteCustomModel,
  getMitmAlias, setMitmAliasAll,
  getPricing, getPricingForModel, updatePricing, resetPricing, resetAllPricing,
  getUsers, getUserById, getUserByEmail, getAdminUser, countUsers,
  createUser, verifyUserPassword, updateUser, setUserStatus, createInvite, consumeInvite, deleteUser,
  getUserSettings, updateUserSettings, getEffectiveSettings,
  exportDb, importDb,
  createBackupDownload, getDatabaseInfo,
} from "@/lib/db/index.js";
